### ISSUE TITLE
Style preprocessing

### ISSUE THREAD

**Issue by marsch-** [schnti/kirby3-cookie#1]
I'm kind of worried that I'm overlooking something, since you just mention
`
@import "../website/site/plugins/cookie/cookie.scss";`

Does Kirby3 have a native preprocessor? If not, how is this intended to be handled?

**Comment by schnti** [comment]
You need an additional SCSS preprocessor. Alternatively, you have to manually translate the SCSS into CSS or use an online compiler: https://www.sassmeister.com #closed

**Comment by marsch-** [comment]
Thank you. It think it would make sense if you mentioned this in the README, since it isn't obvious how your sass becomes css.
